### ISSUE TITLE
Frontend: debug display styling improvement

### ISSUE THREAD

**Issue by dinethmeegoda** [Griddle-Assets/griddle-asset-db#33]
**PLEASE RAIN WE NEED THE DEBUG DISPLAY STYLING PLEASE OUR PROGRAMMERS ARE DYING WITHOUT IT**

**Comment by printer83mph** [comment]
@xcupsilon we really need this feature could you give an ETA on it

**Comment by printer83mph** [comment]
i think this may be not real guys
