### ISSUE TITLE
Implement user accounts

### ISSUE THREAD

**Issue by printer83mph** [Griddle-Assets/griddle-asset-db#42]
- [x] Frontend
  - [x] Forms for login/signup
  - [x] Logout button - full user pipeline
  - [x] Make backend calls from forms
  - [x] Store auth token, add to API calls that require it

- [x] Backend
  - [x] Add users to database models (or find other solution)
  - [x] Add signup, login, logout, and GET auth routes
  - [x] Add auth token requirement to mutation routes
  - [x] Possibly add HASHING to passwords

**Comment by debbylin02** [comment]
created users table in db: 
![image](https://github.com/Griddle-Assets/griddle-asset-db/assets/82790216/18030335-cc74-43f0-9b54-3a42215bcf40)
