### ISSUE TITLE
Add social features

### ISSUE THREAD

**Issue by printer83mph** [Griddle-Assets/griddle-asset-db#54]
- [x] Profile pics on backend
- [x] Profile pics in metadata panel
- [x] Profile pics for users without explicit profile pics chosen shown on dropdown and metadata
- [x] Larger profile pics for the original author of an asset in metadata panel
- [x] Use non-profile pic icon only for non-logged in users in user drop down
- [ ] User registry with search
- [ ] User info view with contact info + owned assets
- [ ] Links from asset/versions in metadata panel to user info views

**Comment by debbylin02** [comment]
![Image](https://github.com/Griddle-Assets/griddle-asset-db/assets/82790216/634fe5de-befa-4fdc-a9a9-c375f8466592)

added profile pic for non-profile pic having users (uses first letter of pennkey)

**Comment by debbylin02** [comment]
![Image](https://github.com/Griddle-Assets/griddle-asset-db/assets/82790216/00c6ad91-68b1-43c2-9418-421e2d889690) 

![Image](https://github.com/Griddle-Assets/griddle-asset-db/assets/82790216/f1bc3218-2760-410e-bb32-bdc2827d32f5)

display the default non-profile pic in the user drop down for users logged in
